---
- name: Обновление списка пакетов
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Устанавливаем базовые пакеты
  apt:
    name: "{{ system_packages }}"
    state: present

- name: Устанавливаем JDK
  apt:
    name: "{{ java_jdk }}"
    state: present

- name: Устанавливаем Docker
  apt:
    name: "{{ docker }}"
    state: present

- name: Запускаем Docker
  service:
    name: docker
    state: started
    enabled: yes