spring:
  application:
    name: project-for-devops
  datasource:
    username: ${DB_USERNAME:my_user}
    password: ${DB_PASSWORD:my_password}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mydb}
    driver-class-name: org.postgresql.Driver


  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    jdbc:
      dialect: postgresql
    redis:
      cluster:
        nodes:
          - redis-master-1:6379
          - redis-master-2:6379
          - redis-master-3:6379


management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    prometheus:
      access: unrestricted