spring:
  application:
    name: project-for-devops
  datasource:
    username: ${db_username}
    password: ${db_password}
    url: jdbc:postgresql://${db_host}:${db_port}/${db_name}
    driver-class-name: org.postgresql.Driver
#  cache:
#    type: redis   # включаем Redis как кэш
#  data:
#    redis:
#      host: localhost
#      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true