---
- name: Установка PostgreSQL
  apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present
    update_cache: yes


- name: Устанавливаем psycopg2 для Ansible PostgreSQL модуля
  apt:
    name: python3-psycopg2
    state: present

- name: Запуск PostgreSQL
  systemd:
    name: postgresql
    state: started
    enabled: yes
