name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: ./gradlew build
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-jar
          path: build/libs/*.jar

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download jar
        uses: actions/download-artifact@v3
        with:
          name: spring-boot-jar
          path: build/libs/
      - name: Deploy via Ansible
        run: ansible-playbook ansible/playbooks/site.yml \
          -i ansible/inventory/hosts.ini \
          -e action=deploy