name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build jar
        run: ./gradlew build

      - name: Deploy via Ansible
        run: |
          cd ansible
          ansible-playbook -i inventory/hosts.ini playbooks/site.yml -e action=deploy